### ISSUE TITLE
Todo List for pattern#2

### ISSUE THREAD

**Issue by ksingh7** [red-hat-data-services/jumpstart-library#8]
## Todo list for pattern-2 : LPR service

- [ ] Use seldon for model serving
- [ ] Run the service against images-corpus and check on what all images it can detect LP , move those to images
- [ ] currently it takes approx 10s to detect LP (on Karan's MBP), find opportunities to improve infrencing time

**Comment by ksingh7** [comment]
# Todo List - Phase-II

- [ ] Pack trino binary in a container image and deploy that, such that users do not need to download it locally and run commands to create schema and table for Hive
- [ ] A better approach for the above point, would be to have a k8s job do all of the above in an automated fashion
